[package]
org = "nuvindu"
name = "pubsub"
version = "@toml.version@"
authors = ["Nuvindu"]
keywords = ["pubsub"]
repository = "https://github.com/Nuvindu/module-pubsub"
license = ["Apache-2.0"]
distribution = "2201.0.1"

[[dependency]]
org = "nuvindu"
name = "pipe"
version = "0.1.0"
repository = "local"
