[package]
org = "xlibb"
name = "pubsub"
version = "1.1.0"
authors = ["xlibb"]
keywords = ["pubsub"]
repository = "https://github.com/xlibb/module-pubsub"
license = ["Apache-2.0"]
distribution = "2201.2.0"
icon = "icon.png"

[[platform.java11.dependency]]
path = "../native/build/libs/pubsub-native-1.1.0-SNAPSHOT.jar"
